<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AwesomeAssertions.Analyzers.CodeFixers\AwesomeAssertions.Analyzers.CodeFixers.csproj" />
    <ProjectReference Include="..\AwesomeAssertions.Analyzers.TestUtils\AwesomeAssertions.Analyzers.TestUtils.csproj" />
  </ItemGroup>
  
</Project>
