name: Benchmark tests
on: [pull_request]

permissions:
    contents: write
    deployments: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    if: github.repository == 'awesomeassertions/awesomeassertions.analyzers'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Run benchmark
        run: cd src/AwesomeAssertions.Analyzers.BenchmarkTests && dotnet run -c Release --exporters json --filter '*'

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1.18.0
        with:
          name: AwesomeAssertions.Analyzers Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: src/AwesomeAssertions.Analyzers.BenchmarkTests/BenchmarkDotNet.Artifacts/results/AwesomeAssertions.Analyzers.BenchmarkTests.AwesomeAssertionsBenchmarks-report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
