name: Publish NuGet package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build & Pack NuGet package
        shell: pwsh
        run: |
          $tag = $env:GITHUB_REF.Substring('refs/tags/v'.Length)
          dotnet pack src/AwesomeAssertions.Analyzers/ --output out --configuration Release -p:Version=$tag

      - name: NuGet login
        id: nuget-login
        uses: NuGet/login@v1
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish NuGet package
        shell: bash
        run: dotnet nuget push "out/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{ steps.nuget-login.outputs.NUGET_API_KEY }}" --skip-duplicate
